config/routes.rb
Parcial2::Application.routes.draw do
  resources :useres

  resources :sabores

  resources :comidas

  resources :promociones

  resources :categorias
  
  resource :user_session

  get "index/Inicio"

  get "index/Historia"

  get "index/Productos"

  get "index/Sucursales"

  get "index/Contacto"
  
  get "index/Acercade"

  get "index/Terminos"
  
  get "index/Mapa"

  
  
  match "index" => "index#Inicio"
  match "quienes" => "index#Historia"
  match "productos" => "index#Productos"
  match "sucursales" => "index#Sucursales"
  match "contacto" => "index#Contacto"
  match "acercade" => "index#Acercade"
  match "terminos" => "index#Terminos"
  match "mapa" => "index#Mapa"
  match "login" => "useres_sessiones#new"
  match "logout" => "useres_sessiones#destroy"

  root :to => 'index#Inicio'

end

app/models/comida.rb
class Comida < ActiveRecord::Base
  belongs_to :categoria
  belongs_to :sabor
  WillPaginate.per_page = 10 
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_authentic
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper :all
  helper_method :current_user_session, :current_user
  protect_from_forgery
  
  helper_method :current_useres

    private
       def current_user_session
         return @current_user_session if defined?(@current_user_session)
         @current_user_session = UserSession.find
       end

       def current_user
         return @current_user if defined?(@current_user)
         @current_user = current_user_session && current_user_session.record
       end

       def require_user
         unless current_user
          # store_location
           flash[:notice] = "You must be logged in to access this page"
           redirect_to new_user_session_url
           return false
         end
       end

       def require_no_user
         if current_user
           store_location
           flash[:notice] = "You must be logged out to access this page"
           redirect_to user_path
           return false
         end
       end

       def store_location
         session[:return_to] = request.request_url
       end

       def redirect_back_or_default(default)
         redirect_to(session[:return_to] || default)
         session[:return_to] = nil
       end
end

app/controllers/comidas_controller.rb
class ComidasController < ApplicationController
  # GET /comidas
  # GET /comidas.json
  def index
    @comidas = Comida.paginate(:page => params[:page], :per_page => 1)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comidas }
    end
  end

  # GET /comidas/1
  # GET /comidas/1.json
  def show
    @comida = Comida.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @comida }
    end
  end

  # GET /comidas/new
  # GET /comidas/new.json
  def new
    @comida = Comida.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @comida }
    end
  end

  # GET /comidas/1/edit
  def edit
    @comida = Comida.find(params[:id])
  end

  # POST /comidas
  # POST /comidas.json
  def create
    @comida = Comida.new(params[:comida])

    respond_to do |format|
      if @comida.save
        format.html { redirect_to @comida, notice: 'Comida was successfully created.' }
        format.json { render json: @comida, status: :created, location: @comida }
      else
        format.html { render action: "new" }
        format.json { render json: @comida.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /comidas/1
  # PUT /comidas/1.json
  def update
    @comida = Comida.find(params[:id])

    respond_to do |format|
      if @comida.update_attributes(params[:comida])
        format.html { redirect_to @comida, notice: 'Comida was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @comida.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comidas/1
  # DELETE /comidas/1.json
  def destroy
    @comida = Comida.find(params[:id])
    @comida.destroy

    respond_to do |format|
      format.html { redirect_to comidas_url }
      format.json { head :ok }
    end
  end
end

app/controllers/useres_controller.rb
class UseresController < ApplicationController
  # GET /useres
  # GET /useres.json
  def index
    @useres = User.paginate(:page => params[:page], :per_page => 6)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @useres }
    end
  end

  # GET /useres/1
  # GET /useres/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /useres/new
  # GET /useres/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /useres/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /useres
  # POST /useres.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /useres/1
  # PUT /useres/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /useres/1
  # DELETE /useres/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to useres_url }
      format.json { head :ok }
    end
  end
end

app/controllers/useres_sessiones_controller.rb
class UseresSessionesController < ApplicationController
  before_filter :require_no_user, :only => [:new, :create]
  before_filter :require_user, :only => :destroy
  
  def new
    @user_session = UserSession.new
  end
  
  def create
    @user_session = UserSession.new(params[:user_session])
    if @user_session.save
      flash[:notice] = "Login successful!"
      redirect_back_or_default root_path
    else
      render :action => :new
    end
  end
  
  def destroy
    current_user_session.destroy
    flash[:notice] = "Logout successful!"
    redirect_back_or_default new_user_session_url
  end
end

app/helpers/useres_helper.rb
module UseresHelper
end

app/helpers/useres_sessiones_helper.rb
module UseresSessionesHelper
end

app/views/categorias/edit.html.erb
<h2 id="cosa"> Editar Categoria</h2>
<div id="editarcate">


<%= render 'form' %>

<%= link_to 'Show', @categoria %> |
<%= link_to 'Back', categorias_path %>
</div>

app/views/categorias/index.html.erb
<h2 id="cosa"> Lista de Categorias </h2>
<div id="listacate">

<table>
  <tr>
    <th>Nombre</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @categorias.each do |categoria| %>
  <tr>
    <td><%= categoria.nombre %></td>
    <td><%= link_to 'Show', categoria %></td>
    <td><%= link_to 'Edit', edit_categoria_path(categoria) %></td>
    <td><%= link_to 'Destroy', categoria, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Categoria', new_categoria_path %>


</div>

app/views/categorias/new.html.erb
<h2 id="cosa"> Categoria Nueva</h2>
<div id="nuevacate">
<%= render 'form' %>

<%= link_to 'Back', categorias_path %>


</div>

app/views/categorias/show.html.erb
<h2 id="cosa"> Categoria</h2>
<div id="showcate">
<p id="notice"><%= notice %></p>

<p>
  <b>Nombre:</b>
  <%= @categoria.nombre %>
</p>


<%= link_to 'Edit', edit_categoria_path(@categoria) %> |
<%= link_to 'Back', categorias_path %>

</div>

app/views/comidas/edit.html.erb
<h2 id="cosa"> Editar Producto</h2>
<div id="editarcomida">
<%= render 'form' %>

<%= link_to 'Show', @comida %> |
<%= link_to 'Back', comidas_path %>


</div>

app/views/comidas/index.html.erb
<h2 id="cosa">Lista de Productos</h2>
<div id="listacomida">

<table>
  <tr>
    <th>Titulo</th>
    <th>Categoria</th>
    <th>Sabor</th>
    <th>Precio</th>
    <th>Descripcion</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @comidas.each do |comida| %>
  <tr>
    <td><%= comida.titulo %></td>
    <td><%= comida.categoria %></td>
    <td><%= comida.sabor %></td>
    <td><%= comida.precio %></td>
    <td><%= comida.descripcion %></td>
    <td><%= link_to 'Show', comida %></td>
    <td><%= link_to 'Edit', edit_comida_path(comida) %></td>
    <td><%= link_to 'Destroy', comida, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>
<%= will_paginate @comidas %>
<br />

<%= link_to 'New Comida', new_comida_path %>


</div>

app/views/comidas/lista.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Titulo:</b>
  <%= @comida.titulo %>
</p>

<p>
  <b>Categoria:</b>
  <%= @comida.categoria %>
</p>

<p>
  <b>Sabor:</b>
  <%= @comida.sabor %>
</p>

<p>
  <b>Precio:</b>
  <%= @comida.precio %>
</p>

<p>
  <b>Descripcion:</b>
  <%= @comida.descripcion %>
</p>


<%= link_to 'Edit', edit_comida_path(@comida) %> |
<%= link_to 'Back', comidas_path %>

app/views/comidas/new.html.erb
<h2 id="cosa"> Agregar Producto</h2>
<div id="nuevacomida">
<%= render 'form' %>

<%= link_to 'Back', comidas_path %>

</div>

app/views/comidas/show.html.erb
<h2 id="cosa">Informacion de Producto</h2>
<div id="vista1comida">
<p id="notice"><%= notice %></p>

<p>
  <b>Titulo:</b>
  <%= @comida.titulo %>
</p>

<p>
  <b>Categoria:</b>
  <%= @comida.categoria %>
</p>

<p>
  <b>Sabor:</b>
  <%= @comida.sabor %>
</p>

<p>
  <b>Precio:</b>
  <%= @comida.precio %>
</p>

<p>
  <b>Descripcion:</b>
  <%= @comida.descripcion %>
</p>


<%= link_to 'Edit', edit_comida_path(@comida) %> |
<%= link_to 'Back', comidas_path %>

</div>

app/views/index/Acercade.html.erb
<h2 id="cosa"> Acerca del Sitio</h2>	
<div id="acerca">
	
</div>

app/views/index/Contacto.html.erb
<h2 id="cosa">Si tienes preguntas o aclaraciones, ponte en contacto con nosotros!</h2>
<div id="contacto">
	<div id="fotocontacto">
	<%= image_tag "pastelfeliz.png"%>
	
	</div>
	
	<link rel="shortcut icon" href="icono.ico">
 <%= stylesheet_link_tag    "view" %>

<script type="text/javascript">
		
		
		
		function verificarCampos(){
			if(document.getElementById("nombre").value != ""){
				if(document.getElementById("correo").value != ""){
					document.frmContacto.submit();
				}else{
					alert("Por favor agrega tu Nombre y/o E-mail.");
				}
			}else{
				alert("Por favor agrega tu Nombre y/o E-mail.");
			}
		}
	</script>


	<div id="form_container">
	
		
		
		
	
		<form id="form_177836" class="appnitro"  method="post" action="enviar.php" name="frmContacto">
					<div class="form_description">
		
			<p>Gracias por interesarte en nosotros. Tus sugerencias y comentarios nos ayudan a mejorar la calidad de nuestros productos y servicios.

Esperamos tus comentarios, o escr&#237;benos a <b>contacto@elglobo.com.mx</b></p>
		</div>						
			<ul >
					<li id="li_1" >
		<label class="description" for="element_1">*Nombre Completo </label>
		<div>
			<input id="nombre" name="nombre" class="element text medium" type="text" maxlength="255" value=""/> 
		</div> 
		</li>		<li id="li_2" >
		<label class="description" for="element_2">Tel&#233;fono </label>
		<div>
			<input id="telefono" name="telefono" class="element text medium" type="text" maxlength="255" value=""/> 
		</div> 
		</li>		<li id="li_3" >
		<label class="description" for="element_3">*Correo Electr&#243;nico </label>
		<div>
			<input id="correo" name="correo" class="element text medium" type="text" maxlength="255" value=""/> 
		</div> 
		</li>		<li id="li_8" >
		<label class="description" for="element_8">Estado </label>
		<div>
			<input id="estado" name="estado" class="element text medium" type="text" maxlength="255" value=""/> 
		</div> 
		</li>		<li id="li_4" >
		<label class="description" for="element_4">Comentarios </label>
		<div>
			<textarea id="comentarios" name="comentarios" class="element textarea medium"></textarea> 
		</div> 
		</li>
			
					<li class="buttons">
				   <input type="hidden" name="form_id" value="177836" />
				   
				<input id="saveForm" class="button_text" type="button" name="enviar" onclick= verificarCampos(); value="Enviar" />
		</li>
			</ul>
		</form>	
	</div>
</div>

app/views/index/Historia.html.erb
<h2 id="cosa"> Quienes Somos?</h2>
	<div id="quienes">
		<div id="quienesfotos">
			<%= image_tag "quien1.jpg" , :size => "280x170" %>
			<br />
			<br />

			<%= image_tag "quien2.jpg", :size => "280x170"%>
		</div>
	<h3> Panaderia el Globo </h3>
	<div id="textoquien">	
	El hombre en sus inicios fue frutivoro y granivoro. Al principio comia los granos tal y como se encuentran en la naturaleza, despues se inicio en el cultivo de los cereales.
Cuando el hombre descubrio el fuego, comenzo a cocer los granos en agua, mas tarde, se le ocurrio pasarlos por el fuego para asarlos y finalmente comenzo a despojar los granos de su corteza y molerlos con dos piedras.<br /><br />

La ruda harina obtenida de este modo, era humedecida para hacer una especie de galleta sin forma, mezclada con salvado. Ese fue el pan que alimento al hombre durante milenios. Los historiadores estan de acuerdo en que el verdadero pan, el pan fermentado, fue inventado por los egipcios, por casualidad.<br /><br />


Cuentan que una esclava olvido hornear un pedazo de masa y al dia siguiente, para evitar el castigo de su amo, metio este pedazo de masa del dia anterior (ya fermentado), en la masa nueva. Hubo una gran sorpresa, porque ese dia, el pan era mucho mejor, con lo cual, el pan fermentado... habia nacido.	<br /> <br />

El arte de hacer pan fue llevado a la Galia por los ejercitos de Julio Cesar, hasta el momento en que los romanos fueron expulsados, es decir, en el siglo V, no sabemos nada en concreto sobre el estado en que se encontraba la elaboracion del pan, lo unico que se sabe es que con el pretexto de economizar, los pueblos riberenos amasaban la harina con agua de mar. 
	</div>
</div>

app/views/index/Inicio.html.erb
<div id="contenido">
		<div id="contenido1">
			<div id="header"><div class="wrap">
   				<div id="slide-holder">
					<div id="slide-runner">
					    <img id="slide-img-1" <%= image_tag "img1.jpg"%> class="slide" alt="" />
						<img id="slide-img-2" <%= image_tag "img2.jpg"%> class="slide" alt="" />
					    <img id="slide-img-3" <%= image_tag "img3.jpg"%> class="slide" alt="" />
					    <img id="slide-img-4" <%= image_tag "img4.jpg"%> class="slide" alt="" />
					    <img id="slide-img-5" <%= image_tag "img1.jpg"%> class="slide" alt="" />
					    <img id="slide-img-6" <%= image_tag "img2.jpg"%> class="slide" alt="" />
						<img id="slide-img-7" <%= image_tag "img3.jpg"%> class="slide" alt="" />
						    <div id="slide-controls">
						     <p id="slide-client" class="text"><strong></strong><span></span></p>
						     <p id="slide-desc" class="text"></p>
						     <p id="slide-nav"></p>
						    </div>
					</div>
				
	
	<!--content featured gallery here -->
   				</div>
  			 <script type="text/javascript">
   			 if(!window.slider) var slider={};slider.data=[{"id":"slide-img-1","client":"Pasteles de la Temporada","desc":"Tu mejor opcion para las fiestas."},{"id":"slide-img-2","client":"Pasteles de tu Deporte","desc":"Tu mejor opcion para las fiestas."},{"id":"slide-img-3", "client":"Pasteles para los ninos","desc":"Tu mejor opcion para las fiestas."},{"id":"slide-img-4","client":"Pasteles de la Temporada","desc":"Tu mejor opcion para las fiestas."},{"id":"slide-img-5","client":"Pasteles de la Temporada","desc":"Pasteles para tu Deporte."},{"id":"slide-img-6","client":"Pasteles de la Temporada","desc":"Tu mejor opcion para las fiestas."},{"id":"slide-img-7","client":"Pasteles de la Temporada","desc":"Tu mejor opcion para las fiestas."}];
   			 </script>
   			 </div>
   			</div>
		</div>
		<h2 id="cosa2"> Promociones</h2>
		
		
		<div id="contenido2">
			
		</div>
	</div>
	

app/views/index/Mapa.html.erb
<h2 id="cosa"> Mapa del Sitio </h2>
<div id="mapadesitio">

	
</div>

app/views/index/Productos.html.erb
<h2 id="cosa"> Nuestros Productos</h2>
<div id="productos">
	

</div>

app/views/index/Sucursales.html.erb
<h2 id="cosa"> Busque la tienda mas cercana a usted</h2>
<div id="sucursales">
	<h3> Seleccione su Estado </h3>		
</div>

app/views/index/Terminos.html.erb
<h2 id="cosa"> Terminos y Condiciones</h2>	
<div id="terminos">
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />

  <title>Pastelerías El Globo</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= javascript_include_tag "jqbanner" %>
  <%= stylesheet_link_tag    "jqbanner" %>
  
  <%= javascript_include_tag "gale2" %>
  <%= stylesheet_link_tag    "gale2" %>
   <%= stylesheet_link_tag    "login" %>
   <%= stylesheet_link_tag    "comidas" %>
  

  

</head>
<body>
<div  id="contenedor" >
	<div id="headerr">
		<div  id="login" >
			<%= link_to_unless_current "Registrarse", new_user_path %> |
			<% if !current_user %>
				<%= link_to "Iniciar Sesión", login_path %>
				<% else %>
				
				<%= link_to_unless_current "Usuarios", useres_path %> |
				<%= link_to "Editar Perfil", edit_user_path(current_user) %> |
				<%= link_to "Cerrar Sesión", logout_path %>
				<% end %>
		</div>
		<div id="imgmenu">
			<%= image_tag "header.png", :size=> "947x218"%>
			<div id="logo">
				<%= link_to (image_tag "logo.png", :size=> "150x150"), root_path%>
			</div>
			<div id="menu">
				<div id="boton1">
					<a><%= link_to (image_tag "inicio.png"), index_path%></a>
				</div>
				<div id="boton2">
					<a><%= link_to (image_tag "productos.png"), productos_path%></a>
				</div>
				<div id="boton3">
					<a><%= link_to (image_tag "quienes.png"), quienes_path%></a>
				</div>
				<div id="boton4">
					<a><%= link_to (image_tag "sucursales.png", :size=> "105x15"), sucursales_path%></a>
				</div>
			</div>
		</div>
		<div id="iconitos">
			<a href="http://www.twitter.com"><%= image_tag "twitter.png", :size=> "40x40"%></a>
			<a href="http://www.facebook.com"><%= image_tag "facebook.png", :size=> "40x40"%></a>
			<%=link_to (image_tag "contacto.png", :size=> "40x40"), contacto_path%>
		</div>
	</div>
	
	
<%= yield %>
	<div id="footer">
		<ul id="menusillo">
			<li><%= link_to "Acerca del Sitio", acercade_path%></li>
			<li><%= link_to "Términos y Condiciones", terminos_path%></li>
			<li><%= link_to "Mapa del Sitio", mapa_path%></li>
		</ul>
		<p>2011® Todos los derechos reservados.©</p>
	</div>
</div>


</body>
</html>

app/views/promociones/edit.html.erb
<h2 id="cosa">Editar Promocion</h2>
<div id="nuevapromo">
<%= render 'form' %>

<%= link_to 'Show', @promocion %> |
<%= link_to 'Back', promociones_path %>


</div>

app/views/promociones/index.html.erb
<h2 id="cosa"> Lista de Promociones</h2>
<div id="listapromo">

<table>
  <tr>
    <th>Titulo</th>
    <th>Descripcion</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @promociones.each do |promocion| %>
  <tr>
    <td><%= promocion.titulo %></td>
    <td><%= promocion.descripcion %></td>
    <td><%= link_to 'Show', promocion %></td>
    <td><%= link_to 'Edit', edit_promocion_path(promocion) %></td>
    <td><%= link_to 'Destroy', promocion, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Promocion', new_promocion_path %>

</div>

app/views/promociones/new.html.erb
<h2 id="cosa">Nueva Promocion</h2>
<div id="nuevapromo">

<%= render 'form' %>

<%= link_to 'Back', promociones_path %>

</div>

app/views/promociones/show.html.erb
<h2 id="cosa">Editar Promocion</h2>
<div id="nuevapromo">
<p id="notice"><%= notice %></p>

<p>
  <b>Titulo:</b>
  <%= @promocion.titulo %>
</p>

<p>
  <b>Descripcion:</b>
  <%= @promocion.descripcion %>
</p>


<%= link_to 'Edit', edit_promocion_path(@promocion) %> |
<%= link_to 'Back', promociones_path %>



</div>

app/views/sabores/edit.html.erb
<h2 id="cosa"> Editar Sabor</h2>
<div id="nuevosabores">

<%= render 'form' %>

<%= link_to 'Show', @sabor %> |
<%= link_to 'Back', sabores_path %>



</div>

app/views/sabores/index.html.erb
<h2 id="cosa"> Lista Sabores</h2>
<div id="listasabores">


<table>
  <tr>
    <th>Sabor1</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sabores.each do |sabor| %>
  <tr>
    <td><%= sabor.sabor1 %></td>
    <td><%= link_to 'Show', sabor %></td>
    <td><%= link_to 'Edit', edit_sabor_path(sabor) %></td>
    <td><%= link_to 'Destroy', sabor, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Sabor', new_sabor_path %>

</div>

app/views/sabores/new.html.erb
<h2 id="cosa"> Lista Sabores</h2>
<div id="nuevosabores">


<%= render 'form' %>

<%= link_to 'Back', sabores_path %>

</div>

app/views/sabores/show.html.erb
<h2 id="cosa"> Lista Sabores</h2>
<div id="nuevosabores">

<p id="notice"><%= notice %></p>

<p>
  <b>Sabor1:</b>
  <%= @sabor.sabor1 %>
</p>


<%= link_to 'Edit', edit_sabor_path(@sabor) %> |
<%= link_to 'Back', sabores_path %>


</div>

app/views/useres/_form.html.erb
<b>
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> Usuario ocupado, elija otro</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
 <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</b>

app/views/useres/edit.html.erb
<h2 id="cosachiqui">Cambiar Datos</h2>
<div id="editauser">

<%= render 'form' %>
<%= link_to 'Cancelar', useres_path %>


</div>

app/views/useres/index.html.erb
<h2 id="cosachiqui">Lista de Usuarios</h2>
<div id="listauser">

<table>

  <tr>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @useres.each do |user| %>
  <tr>
    <td><%= user.email %></td>
    <td><%= link_to 'Mostrar', user %></td>
    <td><%= link_to 'Editar', edit_user_path(user) %></td>
    <td><%= link_to 'Eliminar', user, confirm: 'Estas seguro?', method: :delete %></td>
  </tr>
<% end %>
</table>
<%= will_paginate @useres, :previous_label => '<< Atras', :next_label => 'Siguiente >>'  %>

<br />



</div>

app/views/useres/new.html.erb
<h2 id="cosachiqui">Crear Usuario</h2>
<div id="crearuser">

<%= render 'form' %>


</div>

app/views/useres/show.html.erb
<h2 id="cosachiqui">Crear Usuario</h2>
<div id="crearuser">

<b><p id="notice"><%= notice %></p></b>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>


<%= link_to 'Editar', edit_user_path(@user) %> |
<%= link_to 'Cancelar', useres_path %>



</div>

app/views/useres_sessiones/new.html.erb
<h2 id="cosachiqui">Iniciar Sesion</h2>
<div id="loginform">
<%= form_for @user_session, :url => user_session_path do |f| %>

  <%= f.label :email %><br />
  <%= f.text_field :email %><br />
  <br />
  <%= f.label :password %><br />
  <%= f.password_field :password %><br />
  <br />
  <%= f.check_box :remember_me %><%= f.label :remember_me %><br />
  <br />
  <%= f.submit "Login" %>
<% end %>
	
</div>